#!/bin/sh

# Get the name of the file to check
file=".version"

# Check if the file has been modified
if ! git diff --quiet --exit-code --cached $file; then
    # Get the current version number
    version=$(cat $file)
    # Increment the last number
    new_version=$(echo $version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
    # Update the file with the new version number
    echo $new_version > $file
    git add $file
    git commit -m "Bump version to $new_version"
fi

exit 0